module.exports = {
  setMuteRole:{
    name:'setMuteRole',
    aliases:[],
    cooldown:10,
    description:'ミュート用ロールをセット(できない場合はロールの位置を確認してください)',
    disabled:false
  },mute:{
    name:'mute',
    aliases:[],
    cooldown:10,
    description:'ユーザーをミュート',
    disabled:false
  },voiceBan:{
    name:'voiceBan',
    aliases:[],
    cooldown:10,
    description:'ユーザーをボイスチャンネルのみBan',
    disabled:false
  },kick:{
    name:'kick',
    aliases:[],
    cooldown:10,
    description:'ユーザーをキック',
    disabled:false
  },ban:{
    name:'ban',
    aliases:[],
    cooldown:10,
    description:'ユーザーをバン',
    disabled:false
  },softBan:{
    name:'softBan',
    aliases:[],
    cooldown:10,
    description:'ユーザーを日数指定してバン',
    disabled:false
  },
}